# Python Insights - Analisando Dados com Python

### Case - Cancelamento de Clientes

Você foi contratado por uma empresa com mais de 800 mil clientes para um projeto de Dados. Recentemente a empresa percebeu que da sua base total de clientes, a maioria são clientes inativos, ou seja, que já cancelaram o serviço.

Precisando melhorar seus resultados ela quer conseguir entender os principais motivos desses cancelamentos e quais as ações mais eficientes para reduzir esse número.

Base de dados e arquivos: https://drive.google.com/drive/folders/1uDesZePdkhiraJmiyeZ-w5tfc8XsNYFZ?usp=drive_link

In [2]:
import pandas as pd

df=pd.read_csv("cancelamentos.csv")

display(df)

,CustomerID,idade,sexo,tempo_como_cliente,frequencia_uso,ligacoes_callcenter,dias_atraso,assinatura,duracao_contrato,total_gasto,meses_ultima_interacao,cancelou
0,2.0,30.0,Female,39.0,14.0,5.0,18.0,Standard,Annual,932.00,17.0,1.0
1,3.0,65.0,Female,49.0,1.0,10.0,8.0,Basic,Monthly,557.00,6.0,1.0
2,4.0,55.0,Female,14.0,4.0,6.0,18.0,Basic,Quarterly,185.00,3.0,1.0
3,5.0,58.0,Male,38.0,21.0,7.0,7.0,Standard,Monthly,396.00,29.0,1.0
4,6.0,23.0,Male,32.0,20.0,5.0,8.0,Basic,Monthly,617.00,20.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
881661,449995.0,42.0,Male,54.0,15.0,1.0,3.0,Premium,Annual,716.38,8.0,0.0
881662,449996.0,25.0,Female,8.0,13.0,1.0,20.0,Premium,Annual,745.38,2.0,0.0
881663,449997.0,26.0,Male,35.0,27.0,1.0,5.0,Standard,Quarterly,977.31,9.0,0.0
881664,449998.0,28.0,Male,55.0,14.0,2.0,0.0,Standard,Quarterly,602.55,2.0,0.0
881665,449999.0,31.0,Male,48.0,20.0,1.0,14.0,Premium,Quarterly,567.77,21.0,0.0

In [6]:
display(df.info())

df=df.dropna()

display(df.info())

<class 'pandas.core.frame.DataFrame'>
Index: 881659 entries, 0 to 881665
Data columns (total 12 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   CustomerID              881659 non-null  float64
 1   idade                   881659 non-null  float64
 2   sexo                    881659 non-null  object
 3   tempo_como_cliente      881659 non-null  float64
 4   frequencia_uso          881659 non-null  float64
 5   ligacoes_callcenter     881659 non-null  float64
 6   dias_atraso             881659 non-null  float64
 7   assinatura              881659 non-null  object
 8   duracao_contrato        881659 non-null  object
 9   total_gasto             881659 non-null  float64
 10  meses_ultima_interacao  881659 non-null  float64
 11  cancelou                881659 non-null  float64
dtypes: float64(9), object(3)
memory usage: 87.4+ MB

None

<class 'pandas.core.frame.DataFrame'>
Index: 881659 entries, 0 to 881665
Data columns (total 12 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   CustomerID              881659 non-null  float64
 1   idade                   881659 non-null  float64
 2   sexo                    881659 non-null  object
 3   tempo_como_cliente      881659 non-null  float64
 4   frequencia_uso          881659 non-null  float64
 5   ligacoes_callcenter     881659 non-null  float64
 6   dias_atraso             881659 non-null  float64
 7   assinatura              881659 non-null  object
 8   duracao_contrato        881659 non-null  object
 9   total_gasto             881659 non-null  float64
 10  meses_ultima_interacao  881659 non-null  float64
 11  cancelou                881659 non-null  float64
dtypes: float64(9), object(3)
memory usage: 87.4+ MB

None

In [ ]:
display(df["cancelou"].value_counts())

display(df["cancelou"].value_counts(normalize=True))

sexo
Male      500501
Female    381158
Name: count, dtype: int64

sexo
Male      0.567681
Female    0.432319
Name: proportion, dtype: float64

In [ ]:
import plotly_express as px
import plotly.io as pio

pio.renderers.default = 'browser'

for coluna in df.columns:

    grafico=px.histogram(df,x="",color="cancelou")

    grafico.show()

ValueError: Value of 'x' is not the name of a column in 'data_frame'. Expected one of ['CustomerID', 'idade', 'sexo', 'tempo_como_cliente', 'frequencia_uso', 'ligacoes_callcenter', 'dias_atraso', 'assinatura', 'duracao_contrato', 'total_gasto', 'meses_ultima_interacao', 'cancelou'] but received: column